##
## Build
##

FROM golang:1.16-alpine AS build

WORKDIR /app

COPY go.mod go.sum* .
RUN go mod download

COPY *.go ./

RUN go build -o /helloserver


##
## Deploy
##

FROM golang:1.16-alpine

WORKDIR /app

COPY --from=build /helloserver /helloserver

EXPOSE 8080

USER nonroot:nonroot

CMD [ "/helloserver" ]
